project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
    - "posts/**/index.qmd"
    - "!about.qmd"
    - "!posts/meds-story/index.qmd"

website:
  title: "Emily Miller"
  site-url: https://rellimylime.github.io
  page-footer:
    left: "Made with Quarto, GitHub Pages, and love."
    right: "[Colophon](/colophon.html)"
  navbar:
    left:
      - href: index.qmd
        text: "Home"
      - href: blog.qmd
        text: "Blog"
      - text: "Bona Fides"
        menu:
        - href: research.qmd
          text: "Research"
        - href: cv.qmd
          text: "Resume"
      - text: "Creative"
        menu:
          - href: art.qmd
            text: "Art & Poetry"
          - href: adventures.qmd
            text: "Outside the Lab"
    right:
      - icon: github
        href: https://github.com/rellimylime
        aria-label: "GitHub"

format:
  html:
    theme: styles.scss
    toc: false
    page-layout: article
    include-after-body: site-scripts.html

execute:
  freeze: auto

editor: visual

